name: LootPlus
version: 1.2.1
description: A plugin which enhances loot in various ways
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.LootPlus.LootPlus
commands:
   tweaks:
      description: Displays the tweaks implemented by LootPlus on the server
      usage: /<command>
      permission: LootPlus.tweaks
      permission-message: You don't have permission
      aliases: [tweak, change, changes]
   lpupdate:
      description: Forcefully updates the LootPlus plugin
      usage: /<command>
      permission: LootPlus.lpupdate
      permission-message: You don't have permission

permissions:
   LootPlus.*:
        description: Gives access to all LootPlus commands
        children:
            LootPlus.tweaks: true
   LootPlus.tweaks:
      description: Displays the tweaks implemented by LootPlus on the server
      default: true
   LootPlus.lpupdate:
      description: Forcefully updates the LootPlus plugin