name: LootPlus
version: v1.2.0
description: A plugin which enhances loot in various ways
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.LootPlus.LootPlus
commands:
   tweaks:
      description: Displays the tweaks implemented by LootPlus on the server
      usage: /<command>
      permission: LootPlus.tweaks
      permission-message: You don't have permission
      aliases: [tweak, change, changes]
   lpupdate:
      description: Forcefully updates the LootPlus plugin
      usage: /<command>
      permission: LootPlus.lpupdate
      permission-message: You don't have permission
   add-loot:
      description: Adds new loot to the game, in-game (sets allowCustomDrops to true)
      usage: /<command> dungeon <probability (percentage)> <loot (Material form)> or /<command> mob <mob name> <probability (percentage)> <loot (Material form)>
      permission: LootPlus.add-loot
      permission-message: You don't have permission
      aliases: [addloot, newloot, new-loot, setloot, set-loot]
   set-xp:
      description: Sets the amount of xp dropped by a mob (sets allowCustomXP to true)
      usage: /<command> <mob> <xp>
      permission: LootPlus.set-xp
      permission-message: You don't have permission
      aliases: [setxp, change-xp, changexp]

permissions:
   LootPlus.*:
        description: Gives access to all LootPlus commands
        children:
            LootPlus.tweaks: true
   LootPlus.tweaks:
      description: Displays the tweaks implemented by LootPlus on the server
      default: true
   LootPlus.lpupdate:
      description: Forcefully updates the LootPlus plugin
   LootPlus.add-loot:
      description: Adds new loot to the game, in-game (sets allowCustomDrops to true)
   LootPlus.set-xp:
      description: Sets the amount of xp dropped by a mob (sets allowCustomXP to true)